### ISSUE TITLE
gTTSError: Failed to connect

### ISSUE THREAD

**Issue by OhaDerErste** [Asudox/LemmyCTTS#2]
Tried running this script and I got this error:
```  
2023-10-04 16:55:56.098 | ERROR    | createTTS:createTTS:29 - An error occurred while converting text-to-speech
gTTSError: Failed to connect. Probable cause: Unknown
``` 
Im on Archlinux and Im using python 3.11

**Comment by Asudox** [comment]
> Tried running this script and I got this error:
> ```  
> 2023-10-04 16:55:56.098 | ERROR    | createTTS:createTTS:29 - An error occurred while converting text-to-speech
> gTTSError: Failed to connect. Probable cause: Unknown
> ``` 
> Im on Archlinux and Im using python 3.11

This most likely has something to do with your internet connectivity. gTTS needs internet to work, so perhaps you forgot to turn on the intrrnet? If not, I'll boot up arch linux to see if it works on it at all.

**Comment by OhaDerErste** [comment]
My pihole seems to have blocked translate.google.com. Whitelisting worked. Sorry for bothering you

**Comment by Asudox** [comment]
> My pihole seems to have blocked translate.google.com. Whitelisting worked. Sorry for bothering you

No problem. Have a good day.
